/* eslint-disable camelcase */
export const countries = [
  {
    alpha_2_code: 'WLD',
    alpha_3_code: 'World',
    country_code: '+000',
    en_short_name: 'Worldwide',
    nationality: 'Worldwide',
  },
  {
    alpha_2_code: 'AF',
    alpha_3_code: 'AFG',
    country_code: '+93',
    en_short_name: 'Afghanistan',
    nationality: 'Afghan',
  },
  {
    alpha_2_code: 'AX',
    alpha_3_code: 'ALA',
    country_code: '+358',
    en_short_name: 'Åland Islands',
    nationality: 'Åland Island',
  },
  {
    alpha_2_code: 'AL',
    alpha_3_code: 'ALB',
    country_code: '+355',
    en_short_name: 'Albania',
    nationality: 'Albanian',
  },
  {
    alpha_2_code: 'DZ',
    alpha_3_code: 'DZA',
    country_code: '+213',
    en_short_name: 'Algeria',
    nationality: 'Algerian',
  },
  {
    alpha_2_code: 'AS',
    alpha_3_code: 'ASM',
    country_code: '+1684',
    en_short_name: 'American Samoa',
    nationality: 'American Samoan',
  },
  {
    alpha_2_code: 'AD',
    alpha_3_code: 'AND',
    country_code: '+376',
    en_short_name: 'Andorra',
    nationality: 'Andorran',
  },
  {
    alpha_2_code: 'AO',
    alpha_3_code: 'AGO',
    country_code: '+244',
    en_short_name: 'Angola',
    nationality: 'Angolan',
  },
  {
    alpha_2_code: 'AI',
    alpha_3_code: 'AIA',
    country_code: '+1264',
    en_short_name: 'Anguilla',
    nationality: 'Anguillan',
  },
  {
    alpha_2_code: 'AQ',
    alpha_3_code: 'ATA',
    country_code: '+672',
    en_short_name: 'Antarctica',
    nationality: 'Antarctic',
  },
  {
    alpha_2_code: 'AG',
    alpha_3_code: 'ATG',
    country_code: '+1268',
    en_short_name: 'Antigua and Barbuda',
    nationality: 'Antiguan or Barbudan',
  },
  {
    alpha_2_code: 'AR',
    alpha_3_code: 'ARG',
    country_code: '+54',
    en_short_name: 'Argentina',
    nationality: 'Argentine',
  },
  {
    alpha_2_code: 'AM',
    alpha_3_code: 'ARM',
    country_code: '+374',
    en_short_name: 'Armenia',
    nationality: 'Armenian',
  },
  {
    alpha_2_code: 'AW',
    alpha_3_code: 'ABW',
    country_code: '+297',
    en_short_name: 'Aruba',
    nationality: 'Aruban',
  },
  {
    alpha_2_code: 'AU',
    alpha_3_code: 'AUS',
    country_code: '+61',
    en_short_name: 'Australia',
    nationality: 'Australian',
  },
  {
    alpha_2_code: 'AT',
    alpha_3_code: 'AUT',
    country_code: '+43',
    en_short_name: 'Austria',
    nationality: 'Austrian',
  },
  {
    alpha_2_code: 'AZ',
    alpha_3_code: 'AZE',
    country_code: '+994',
    en_short_name: 'Azerbaijan',
    nationality: 'Azerbaijani, Azeri',
  },
  {
    alpha_2_code: 'BS',
    alpha_3_code: 'BHS',
    country_code: '+1242',
    en_short_name: 'Bahamas',
    nationality: 'Bahamian',
  },
  {
    alpha_2_code: 'BH',
    alpha_3_code: 'BHR',
    country_code: '+973',
    en_short_name: 'Bahrain',
    nationality: 'Bahraini',
  },
  {
    alpha_2_code: 'BD',
    alpha_3_code: 'BGD',
    country_code: '+880',
    en_short_name: 'Bangladesh',
    nationality: 'Bangladeshi',
  },
  {
    alpha_2_code: 'BB',
    alpha_3_code: 'BRB',
    country_code: '+1246',
    en_short_name: 'Barbados',
    nationality: 'Barbadian',
  },
  {
    alpha_2_code: 'BY',
    alpha_3_code: 'BLR',
    country_code: '+375',
    en_short_name: 'Belarus',
    nationality: 'Belarusian',
  },
  {
    alpha_2_code: 'BE',
    alpha_3_code: 'BEL',
    country_code: '+32',
    en_short_name: 'Belgium',
    nationality: 'Belgian',
  },
  {
    alpha_2_code: 'BZ',
    alpha_3_code: 'BLZ',
    country_code: '+501',
    en_short_name: 'Belize',
    nationality: 'Belizean',
  },
  {
    alpha_2_code: 'BJ',
    alpha_3_code: 'BEN',
    country_code: '+229',
    en_short_name: 'Benin',
    nationality: 'Beninese, Beninois',
  },
  {
    alpha_2_code: 'BM',
    alpha_3_code: 'BMU',
    country_code: '+1441',
    en_short_name: 'Bermuda',
    nationality: 'Bermudian, Bermudan',
  },
  {
    alpha_2_code: 'BT',
    alpha_3_code: 'BTN',
    country_code: '+975',
    en_short_name: 'Bhutan',
    nationality: 'Bhutanese',
  },
  {
    alpha_2_code: 'BO',
    alpha_3_code: 'BOL',
    country_code: '+591',
    en_short_name: 'Bolivia (Plurinational State of)',
    nationality: 'Bolivian',
  },
  {
    alpha_2_code: 'BQ',
    alpha_3_code: 'BES',
    country_code: '+599',
    en_short_name: 'Bonaire, Sint Eustatius and Saba',
    nationality: 'Bonaire',
  },
  {
    alpha_2_code: 'BA',
    alpha_3_code: 'BIH',
    country_code: '+387',
    en_short_name: 'Bosnia and Herzegovina',
    nationality: 'Bosnian or Herzegovinian',
  },
  {
    alpha_2_code: 'BW',
    alpha_3_code: 'BWA',
    country_code: '+267',
    en_short_name: 'Botswana',
    nationality: 'Motswana, Botswanan',
  },
  {
    alpha_2_code: 'BV',
    alpha_3_code: 'BVT',
    country_code: '+55',
    en_short_name: 'Bouvet Island',
    nationality: 'Bouvet Island',
  },
  {
    alpha_2_code: 'BR',
    alpha_3_code: 'BRA',
    country_code: '+55',
    en_short_name: 'Brazil',
    nationality: 'Brazilian',
  },
  {
    alpha_2_code: 'IO',
    alpha_3_code: 'IOT',
    country_code: '+246',
    en_short_name: 'British Indian Ocean Territory',
    nationality: 'BIOT',
  },
  {
    alpha_2_code: 'BN',
    alpha_3_code: 'BRN',
    country_code: '+673',
    en_short_name: 'Brunei Darussalam',
    nationality: 'Bruneian',
  },
  {
    alpha_2_code: 'BG',
    alpha_3_code: 'BGR',
    country_code: '+359',
    en_short_name: 'Bulgaria',
    nationality: 'Bulgarian',
  },
  {
    alpha_2_code: 'BF',
    alpha_3_code: 'BFA',
    country_code: '+226',
    en_short_name: 'Burkina Faso',
    nationality: 'Burkinabé',
  },
  {
    alpha_2_code: 'BI',
    alpha_3_code: 'BDI',
    country_code: '+257',
    en_short_name: 'Burundi',
    nationality: 'Burundian',
  },
  {
    alpha_2_code: 'CV',
    alpha_3_code: 'CPV',
    country_code: '+238',
    en_short_name: 'Cabo Verde',
    nationality: 'Cabo Verdean',
  },
  {
    alpha_2_code: 'KH',
    alpha_3_code: 'KHM',
    country_code: '+855',
    en_short_name: 'Cambodia',
    nationality: 'Cambodian',
  },
  {
    alpha_2_code: 'CM',
    alpha_3_code: 'CMR',
    country_code: '+237',
    en_short_name: 'Cameroon',
    nationality: 'Cameroonian',
  },
  {
    alpha_2_code: 'CA',
    alpha_3_code: 'CAN',
    country_code: '+1',
    en_short_name: 'Canada',
    nationality: 'Canadian',
  },
  {
    alpha_2_code: 'KY',
    alpha_3_code: 'CYM',
    country_code: '+1345',
    en_short_name: 'Cayman Islands',
    nationality: 'Caymanian',
  },
  {
    alpha_2_code: 'CF',
    alpha_3_code: 'CAF',
    country_code: '+236',
    en_short_name: 'Central African Republic',
    nationality: 'Central African',
  },
  {
    alpha_2_code: 'TD',
    alpha_3_code: 'TCD',
    country_code: '+235',
    en_short_name: 'Chad',
    nationality: 'Chadian',
  },
  {
    alpha_2_code: 'CL',
    alpha_3_code: 'CHL',
    country_code: '+56',
    en_short_name: 'Chile',
    nationality: 'Chilean',
  },
  {
    alpha_2_code: 'CN',
    alpha_3_code: 'CHN',
    country_code: '+86',
    en_short_name: 'China',
    nationality: 'Chinese',
  },
  {
    alpha_2_code: 'CX',
    alpha_3_code: 'CXR',
    country_code: '+61',
    en_short_name: 'Christmas Island',
    nationality: 'Christmas Island',
  },
  {
    alpha_2_code: 'CC',
    alpha_3_code: 'CCK',
    country_code: '+61',
    en_short_name: 'Cocos (Keeling) Islands',
    nationality: 'Cocos Island',
  },
  {
    alpha_2_code: 'CO',
    alpha_3_code: 'COL',
    country_code: '+57',
    en_short_name: 'Colombia',
    nationality: 'Colombian',
  },
  {
    alpha_2_code: 'KM',
    alpha_3_code: 'COM',
    country_code: '+269',
    en_short_name: 'Comoros',
    nationality: 'Comoran, Comorian',
  },
  {
    alpha_2_code: 'CG',
    alpha_3_code: 'COG',
    country_code: '+242',
    en_short_name: 'Congo (Republic of the)',
    nationality: 'Congolese',
  },
  {
    alpha_2_code: 'CD',
    alpha_3_code: 'COD',
    country_code: '+243',
    en_short_name: 'Congo (Democratic Republic of the)',
    nationality: 'Congolese',
  },
  {
    alpha_2_code: 'CK',
    alpha_3_code: 'COK',
    country_code: '+682',
    en_short_name: 'Cook Islands',
    nationality: 'Cook Island',
  },
  {
    alpha_2_code: 'CR',
    alpha_3_code: 'CRI',
    country_code: '+506',
    en_short_name: 'Costa Rica',
    nationality: 'Costa Rican',
  },
  {
    alpha_2_code: 'CI',
    alpha_3_code: 'CIV',
    country_code: '+225',
    en_short_name: 'Côte d\'Ivoire',
    nationality: 'Ivorian',
  },
  {
    alpha_2_code: 'HR',
    alpha_3_code: 'HRV',
    country_code: '+385',
    en_short_name: 'Croatia',
    nationality: 'Croatian',
  },
  {
    alpha_2_code: 'CU',
    alpha_3_code: 'CUB',
    country_code: '+53',
    en_short_name: 'Cuba',
    nationality: 'Cuban',
  },
  {
    alpha_2_code: 'CW',
    alpha_3_code: 'CUW',
    country_code: '+5999',
    en_short_name: 'Curaçao',
    nationality: 'Curaçaoan',
  },
  {
    alpha_2_code: 'CY',
    alpha_3_code: 'CYP',
    country_code: '+357',
    en_short_name: 'Cyprus',
    nationality: 'Cypriot',
  },
  {
    alpha_2_code: 'CZ',
    alpha_3_code: 'CZE',
    country_code: '+420',
    en_short_name: 'Czech Republic',
    nationality: 'Czech',
  },
  {
    alpha_2_code: 'DK',
    alpha_3_code: 'DNK',
    country_code: '+45',
    en_short_name: 'Denmark',
    nationality: 'Danish',
  },
  {
    alpha_2_code: 'DJ',
    alpha_3_code: 'DJI',
    country_code: '+253',
    en_short_name: 'Djibouti',
    nationality: 'Djiboutian',
  },
  {
    alpha_2_code: 'DM',
    alpha_3_code: 'DMA',
    country_code: '+1767',
    en_short_name: 'Dominica',
    nationality: 'Dominican',
  },
  {
    alpha_2_code: 'DO',
    alpha_3_code: 'DOM',
    country_code: '+1849',
    en_short_name: 'Dominican Republic',
    nationality: 'Dominican',
  },
  {
    alpha_2_code: 'EC',
    alpha_3_code: 'ECU',
    country_code: '+593',
    en_short_name: 'Ecuador',
    nationality: 'Ecuadorian',
  },
  {
    alpha_2_code: 'EG',
    alpha_3_code: 'EGY',
    country_code: '+20',
    en_short_name: 'Egypt',
    nationality: 'Egyptian',
  },
  {
    alpha_2_code: 'SV',
    alpha_3_code: 'SLV',
    country_code: '+503',
    en_short_name: 'El Salvador',
    nationality: 'Salvadoran',
  },
  {
    alpha_2_code: 'GQ',
    alpha_3_code: 'GNQ',
    country_code: '+240',
    en_short_name: 'Equatorial Guinea',
    nationality: 'Equatorial Guinean, Equatoguinean',
  },
  {
    alpha_2_code: 'ER',
    alpha_3_code: 'ERI',
    country_code: '+291',
    en_short_name: 'Eritrea',
    nationality: 'Eritrean',
  },
  {
    alpha_2_code: 'EE',
    alpha_3_code: 'EST',
    country_code: '+372',
    en_short_name: 'Estonia',
    nationality: 'Estonian',
  },
  {
    alpha_2_code: 'ET',
    alpha_3_code: 'ETH',
    country_code: '+251',
    en_short_name: 'Ethiopia',
    nationality: 'Ethiopian',
  },
  {
    alpha_2_code: 'FK',
    alpha_3_code: 'FLK',
    country_code: '+500',
    en_short_name: 'Falkland Islands (Malvinas)',
    nationality: 'Falkland Island',
  },
  {
    alpha_2_code: 'FO',
    alpha_3_code: 'FRO',
    country_code: '+298',
    en_short_name: 'Faroe Islands',
    nationality: 'Faroese',
  },
  {
    alpha_2_code: 'FJ',
    alpha_3_code: 'FJI',
    country_code: '+679',
    en_short_name: 'Fiji',
    nationality: 'Fijian',
  },
  {
    alpha_2_code: 'FI',
    alpha_3_code: 'FIN',
    country_code: '+358',
    en_short_name: 'Finland',
    nationality: 'Finnish',
  },
  {
    alpha_2_code: 'FR',
    alpha_3_code: 'FRA',
    country_code: '+33',
    en_short_name: 'France',
    nationality: 'French',
  },
  {
    alpha_2_code: 'GF',
    alpha_3_code: 'GUF',
    country_code: '+594',
    en_short_name: 'French Guiana',
    nationality: 'French Guianese',
  },
  {
    alpha_2_code: 'PF',
    alpha_3_code: 'PYF',
    country_code: '+689',
    en_short_name: 'French Polynesia',
    nationality: 'French Polynesian',
  },
  {
    alpha_2_code: 'TF',
    alpha_3_code: 'ATF',
    country_code: '+262',
    en_short_name: 'French Southern Territories',
    nationality: 'French Southern Territories',
  },
  {
    alpha_2_code: 'GA',
    alpha_3_code: 'GAB',
    country_code: '+241',
    en_short_name: 'Gabon',
    nationality: 'Gabonese',
  },
  {
    alpha_2_code: 'GM',
    alpha_3_code: 'GMB',
    country_code: '+220',
    en_short_name: 'Gambia',
    nationality: 'Gambian',
  },
  {
    alpha_2_code: 'GE',
    alpha_3_code: 'GEO',
    country_code: '+995',
    en_short_name: 'Georgia',
    nationality: 'Georgian',
  },
  {
    alpha_2_code: 'DE',
    alpha_3_code: 'DEU',
    country_code: '+49',
    en_short_name: 'Germany',
    nationality: 'German',
  },
  {
    alpha_2_code: 'GH',
    alpha_3_code: 'GHA',
    country_code: '+233',
    en_short_name: 'Ghana',
    nationality: 'Ghanaian',
  },
  {
    alpha_2_code: 'GI',
    alpha_3_code: 'GIB',
    country_code: '+350',
    en_short_name: 'Gibraltar',
    nationality: 'Gibraltar',
  },
  {
    alpha_2_code: 'GR',
    alpha_3_code: 'GRC',
    country_code: '+30',
    en_short_name: 'Greece',
    nationality: 'Greek, Hellenic',
  },
  {
    alpha_2_code: 'GL',
    alpha_3_code: 'GRL',
    country_code: '+299',
    en_short_name: 'Greenland',
    nationality: 'Greenlandic',
  },
  {
    alpha_2_code: 'GD',
    alpha_3_code: 'GRD',
    country_code: '+1473',
    en_short_name: 'Grenada',
    nationality: 'Grenadian',
  },
  {
    alpha_2_code: 'GP',
    alpha_3_code: 'GLP',
    country_code: '+590',
    en_short_name: 'Guadeloupe',
    nationality: 'Guadeloupe',
  },
  {
    alpha_2_code: 'GU',
    alpha_3_code: 'GUM',
    country_code: '+1671',
    en_short_name: 'Guam',
    nationality: 'Guamanian, Guambat',
  },
  {
    alpha_2_code: 'GT',
    alpha_3_code: 'GTM',
    country_code: '+502',
    en_short_name: 'Guatemala',
    nationality: 'Guatemalan',
  },
  {
    alpha_2_code: 'GG',
    alpha_3_code: 'GGY',
    country_code: '+44',
    en_short_name: 'Guernsey',
    nationality: 'Channel Island',
  },
  {
    alpha_2_code: 'GN',
    alpha_3_code: 'GIN',
    country_code: '+224',
    en_short_name: 'Guinea',
    nationality: 'Guinean',
  },
  {
    alpha_2_code: 'GW',
    alpha_3_code: 'GNB',
    country_code: '+245',
    en_short_name: 'Guinea-Bissau',
    nationality: 'Bissau-Guinean',
  },
  {
    alpha_2_code: 'GY',
    alpha_3_code: 'GUY',
    country_code: '+592',
    en_short_name: 'Guyana',
    nationality: 'Guyanese',
  },
  {
    alpha_2_code: 'HT',
    alpha_3_code: 'HTI',
    country_code: '+509',
    en_short_name: 'Haiti',
    nationality: 'Haitian',
  },
  {
    alpha_2_code: 'HM',
    alpha_3_code: 'HMD',
    country_code: '+672',
    en_short_name: 'Heard Island and McDonald Islands',
    nationality: 'Heard Island or McDonald Islands',
  },
  {
    alpha_2_code: 'VA',
    alpha_3_code: 'VAT',
    country_code: '+379',
    en_short_name: 'Vatican City State',
    nationality: 'Vatican',
  },
  {
    alpha_2_code: 'HN',
    alpha_3_code: 'HND',
    country_code: '+504',
    en_short_name: 'Honduras',
    nationality: 'Honduran',
  },
  {
    alpha_2_code: 'HK',
    alpha_3_code: 'HKG',
    country_code: '+852',
    en_short_name: 'Hong Kong',
    nationality: 'Hong Kong, Hong Kongese',
  },
  {
    alpha_2_code: 'HU',
    alpha_3_code: 'HUN',
    country_code: '+36',
    en_short_name: 'Hungary',
    nationality: 'Hungarian, Magyar',
  },
  {
    alpha_2_code: 'IS',
    alpha_3_code: 'ISL',
    country_code: '+354',
    en_short_name: 'Iceland',
    nationality: 'Icelandic',
  },
  {
    alpha_2_code: 'IN',
    alpha_3_code: 'IND',
    country_code: '+91',
    en_short_name: 'India',
    nationality: 'Indian',
  },
  {
    alpha_2_code: 'ID',
    alpha_3_code: 'IDN',
    country_code: '+62',
    en_short_name: 'Indonesia',
    nationality: 'Indonesian',
  },
  {
    alpha_2_code: 'IR',
    alpha_3_code: 'IRN',
    country_code: '+98',
    en_short_name: 'Iran',
    nationality: 'Iranian, Persian',
  },
  {
    alpha_2_code: 'IQ',
    alpha_3_code: 'IRQ',
    country_code: '+964',
    en_short_name: 'Iraq',
    nationality: 'Iraqi',
  },
  {
    alpha_2_code: 'IE',
    alpha_3_code: 'IRL',
    country_code: '+353',
    en_short_name: 'Ireland',
    nationality: 'Irish',
  },
  {
    alpha_2_code: 'IM',
    alpha_3_code: 'IMN',
    country_code: '+44',
    en_short_name: 'Isle of Man',
    nationality: 'Manx',
  },
  {
    alpha_2_code: 'IL',
    alpha_3_code: 'ISR',
    country_code: '+972',
    en_short_name: 'Israel',
    nationality: 'Israeli',
  },
  {
    alpha_2_code: 'IT',
    alpha_3_code: 'ITA',
    country_code: '+39',
    en_short_name: 'Italy',
    nationality: 'Italian',
  },
  {
    alpha_2_code: 'JM',
    alpha_3_code: 'JAM',
    country_code: '+1876',
    en_short_name: 'Jamaica',
    nationality: 'Jamaican',
  },
  {
    alpha_2_code: 'JP',
    alpha_3_code: 'JPN',
    country_code: '+81',
    en_short_name: 'Japan',
    nationality: 'Japanese',
  },
  {
    alpha_2_code: 'JE',
    alpha_3_code: 'JEY',
    country_code: '+44',
    en_short_name: 'Jersey',
    nationality: 'Channel Island',
  },
  {
    alpha_2_code: 'JO',
    alpha_3_code: 'JOR',
    country_code: '+962',
    en_short_name: 'Jordan',
    nationality: 'Jordanian',
  },
  {
    alpha_2_code: 'KZ',
    alpha_3_code: 'KAZ',
    country_code: '+77',
    en_short_name: 'Kazakhstan',
    nationality: 'Kazakhstani, Kazakh',
  },
  {
    alpha_2_code: 'KE',
    alpha_3_code: 'KEN',
    country_code: '+254',
    en_short_name: 'Kenya',
    nationality: 'Kenyan',
  },
  {
    alpha_2_code: 'KI',
    alpha_3_code: 'KIR',
    country_code: '+686',
    en_short_name: 'Kiribati',
    nationality: 'I-Kiribati',
  },
  {
    alpha_2_code: 'KP',
    alpha_3_code: 'PRK',
    country_code: '+850',
    en_short_name: 'Korea (Democratic People\'s Republic of)',
    nationality: 'North Korean',
  },
  {
    alpha_2_code: 'KR',
    alpha_3_code: 'KOR',
    country_code: '+82',
    en_short_name: 'Korea (Republic of)',
    nationality: 'South Korean',
  },
  {
    alpha_2_code: 'XK',
    alpha_3_code: 'XKX',
    country_code: '+383',
    en_short_name: 'Kosovo',
    nationality: 'Kosovan',
  },
  {
    alpha_2_code: 'KW',
    alpha_3_code: 'KWT',
    country_code: '+965',
    en_short_name: 'Kuwait',
    nationality: 'Kuwaiti',
  },
  {
    alpha_2_code: 'KG',
    alpha_3_code: 'KGZ',
    country_code: '+996',
    en_short_name: 'Kyrgyzstan',
    nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz',
  },
  {
    alpha_2_code: 'LA',
    alpha_3_code: 'LAO',
    country_code: '+856',
    en_short_name: 'Lao People\'s Democratic Republic',
    nationality: 'Lao, Laotian',
  },
  {
    alpha_2_code: 'LV',
    alpha_3_code: 'LVA',
    country_code: '+371',
    en_short_name: 'Latvia',
    nationality: 'Latvian',
  },
  {
    alpha_2_code: 'LB',
    alpha_3_code: 'LBN',
    country_code: '+961',
    en_short_name: 'Lebanon',
    nationality: 'Lebanese',
  },
  {
    alpha_2_code: 'LS',
    alpha_3_code: 'LSO',
    country_code: '+266',
    en_short_name: 'Lesotho',
    nationality: 'Basotho',
  },
  {
    alpha_2_code: 'LR',
    alpha_3_code: 'LBR',
    country_code: '+231',
    en_short_name: 'Liberia',
    nationality: 'Liberian',
  },
  {
    alpha_2_code: 'LY',
    alpha_3_code: 'LBY',
    country_code: '+218',
    en_short_name: 'Libya',
    nationality: 'Libyan',
  },
  {
    alpha_2_code: 'LI',
    alpha_3_code: 'LIE',
    country_code: '+423',
    en_short_name: 'Liechtenstein',
    nationality: 'Liechtensteiner',
  },
  {
    alpha_2_code: 'LT',
    alpha_3_code: 'LTU',
    country_code: '+370',
    en_short_name: 'Lithuania',
    nationality: 'Lithuanian',
  },
  {
    alpha_2_code: 'LU',
    alpha_3_code: 'LUX',
    country_code: '+352',
    en_short_name: 'Luxembourg',
    nationality: 'Luxembourg, Luxembourgish',
  },
  {
    alpha_2_code: 'MO',
    alpha_3_code: 'MAC',
    country_code: '+853',
    en_short_name: 'Macao',
    nationality: 'Macanese, Chinese',
  },
  {
    alpha_2_code: 'MK',
    alpha_3_code: 'MKD',
    country_code: '+389',
    en_short_name: 'Macedonia (the former Yugoslav Republic of)',
    nationality: 'Macedonian',
  },
  {
    alpha_2_code: 'MG',
    alpha_3_code: 'MDG',
    country_code: '+261',
    en_short_name: 'Madagascar',
    nationality: 'Malagasy',
  },
  {
    alpha_2_code: 'MW',
    alpha_3_code: 'MWI',
    country_code: '+265',
    en_short_name: 'Malawi',
    nationality: 'Malawian',
  },
  {
    alpha_2_code: 'MY',
    alpha_3_code: 'MYS',
    country_code: '+60',
    en_short_name: 'Malaysia',
    nationality: 'Malaysian',
  },
  {
    alpha_2_code: 'MV',
    alpha_3_code: 'MDV',
    country_code: '+960',
    en_short_name: 'Maldives',
    nationality: 'Maldivian',
  },
  {
    alpha_2_code: 'ML',
    alpha_3_code: 'MLI',
    country_code: '+223',
    en_short_name: 'Mali',
    nationality: 'Malian, Malinese',
  },
  {
    alpha_2_code: 'MT',
    alpha_3_code: 'MLT',
    country_code: '+356',
    en_short_name: 'Malta',
    nationality: 'Maltese',
  },
  {
    alpha_2_code: 'MH',
    alpha_3_code: 'MHL',
    country_code: '+692',
    en_short_name: 'Marshall Islands',
    nationality: 'Marshallese',
  },
  {
    alpha_2_code: 'MQ',
    alpha_3_code: 'MTQ',
    country_code: '+596',
    en_short_name: 'Martinique',
    nationality: 'Martiniquais, Martinican',
  },
  {
    alpha_2_code: 'MR',
    alpha_3_code: 'MRT',
    country_code: '+222',
    en_short_name: 'Mauritania',
    nationality: 'Mauritanian',
  },
  {
    alpha_2_code: 'MU',
    alpha_3_code: 'MUS',
    country_code: '+230',
    en_short_name: 'Mauritius',
    nationality: 'Mauritian',
  },
  {
    alpha_2_code: 'YT',
    alpha_3_code: 'MYT',
    country_code: '+262',
    en_short_name: 'Mayotte',
    nationality: 'Mahoran',
  },
  {
    alpha_2_code: 'MX',
    alpha_3_code: 'MEX',
    country_code: '+52',
    en_short_name: 'Mexico',
    nationality: 'Mexican',
  },
  {
    alpha_2_code: 'FM',
    alpha_3_code: 'FSM',
    country_code: '+691',
    en_short_name: 'Micronesia (Federated States of)',
    nationality: 'Micronesian',
  },
  {
    alpha_2_code: 'MD',
    alpha_3_code: 'MDA',
    country_code: '+373',
    en_short_name: 'Moldova (Republic of)',
    nationality: 'Moldovan',
  },
  {
    alpha_2_code: 'MC',
    alpha_3_code: 'MCO',
    country_code: '+377',
    en_short_name: 'Monaco',
    nationality: 'Monégasque, Monacan',
  },
  {
    alpha_2_code: 'MN',
    alpha_3_code: 'MNG',
    country_code: '+976',
    en_short_name: 'Mongolia',
    nationality: 'Mongolian',
  },
  {
    alpha_2_code: 'ME',
    alpha_3_code: 'MNE',
    country_code: '+382',
    en_short_name: 'Montenegro',
    nationality: 'Montenegrin',
  },
  {
    alpha_2_code: 'MS',
    alpha_3_code: 'MSR',
    country_code: '+1664',
    en_short_name: 'Montserrat',
    nationality: 'Montserratian',
  },
  {
    alpha_2_code: 'MA',
    alpha_3_code: 'MAR',
    country_code: '+212',
    en_short_name: 'Morocco',
    nationality: 'Moroccan',
  },
  {
    alpha_2_code: 'MZ',
    alpha_3_code: 'MOZ',
    country_code: '+258',
    en_short_name: 'Mozambique',
    nationality: 'Mozambican',
  },
  {
    alpha_2_code: 'MM',
    alpha_3_code: 'MMR',
    country_code: '+95',
    en_short_name: 'Myanmar',
    nationality: 'Burmese',
  },
  {
    alpha_2_code: 'NA',
    alpha_3_code: 'NAM',
    country_code: '+264',
    en_short_name: 'Namibia',
    nationality: 'Namibian',
  },
  {
    alpha_2_code: 'NR',
    alpha_3_code: 'NRU',
    country_code: '+674',
    en_short_name: 'Nauru',
    nationality: 'Nauruan',
  },
  {
    alpha_2_code: 'NP',
    alpha_3_code: 'NPL',
    country_code: '+977',
    en_short_name: 'Nepal',
    nationality: 'Nepali, Nepalese',
  },
  {
    alpha_2_code: 'NL',
    alpha_3_code: 'NLD',
    country_code: '+31',
    en_short_name: 'Netherlands',
    nationality: 'Dutch, Netherlandic',
  },
  {
    alpha_2_code: 'NC',
    alpha_3_code: 'NCL',
    country_code: '+687',
    en_short_name: 'New Caledonia',
    nationality: 'New Caledonian',
  },
  {
    alpha_2_code: 'NZ',
    alpha_3_code: 'NZL',
    country_code: '+64',
    en_short_name: 'New Zealand',
    nationality: 'New Zealand, NZ',
  },
  {
    alpha_2_code: 'NI',
    alpha_3_code: 'NIC',
    country_code: '+505',
    en_short_name: 'Nicaragua',
    nationality: 'Nicaraguan',
  },
  {
    alpha_2_code: 'NE',
    alpha_3_code: 'NER',
    country_code: '+227',
    en_short_name: 'Niger',
    nationality: 'Nigerien',
  },
  {
    alpha_2_code: 'NG',
    alpha_3_code: 'NGA',
    country_code: '+234',
    en_short_name: 'Nigeria',
    nationality: 'Nigerian',
  },
  {
    alpha_2_code: 'NU',
    alpha_3_code: 'NIU',
    country_code: '+683',
    en_short_name: 'Niue',
    nationality: 'Niuean',
  },
  {
    alpha_2_code: 'NF',
    alpha_3_code: 'NFK',
    country_code: '+672',
    en_short_name: 'Norfolk Island',
    nationality: 'Norfolk Island',
  },
  {
    alpha_2_code: 'MP',
    alpha_3_code: 'MNP',
    country_code: '+1670',
    en_short_name: 'Northern Mariana Islands',
    nationality: 'Northern Marianan',
  },
  {
    alpha_2_code: 'NO',
    alpha_3_code: 'NOR',
    country_code: '+47',
    en_short_name: 'Norway',
    nationality: 'Norwegian',
  },
  {
    alpha_2_code: 'OM',
    alpha_3_code: 'OMN',
    country_code: '+968',
    en_short_name: 'Oman',
    nationality: 'Omani',
  },
  {
    alpha_2_code: 'PK',
    alpha_3_code: 'PAK',
    country_code: '+92',
    en_short_name: 'Pakistan',
    nationality: 'Pakistani',
  },
  {
    alpha_2_code: 'PW',
    alpha_3_code: 'PLW',
    country_code: '+680',
    en_short_name: 'Palau',
    nationality: 'Palauan',
  },
  {
    alpha_2_code: 'PS',
    alpha_3_code: 'PSE',
    country_code: '+970',
    en_short_name: 'Palestine, State of',
    nationality: 'Palestinian',
  },
  {
    alpha_2_code: 'PA',
    alpha_3_code: 'PAN',
    country_code: '+507',
    en_short_name: 'Panama',
    nationality: 'Panamanian',
  },
  {
    alpha_2_code: 'PG',
    alpha_3_code: 'PNG',
    country_code: '+675',
    en_short_name: 'Papua New Guinea',
    nationality: 'Papua New Guinean, Papuan',
  },
  {
    alpha_2_code: 'PY',
    alpha_3_code: 'PRY',
    country_code: '+595',
    en_short_name: 'Paraguay',
    nationality: 'Paraguayan',
  },
  {
    alpha_2_code: 'PE',
    alpha_3_code: 'PER',
    country_code: '+51',
    en_short_name: 'Peru',
    nationality: 'Peruvian',
  },
  {
    alpha_2_code: 'PH',
    alpha_3_code: 'PHL',
    country_code: '+63',
    en_short_name: 'Philippines',
    nationality: 'Philippine, Filipino',
  },
  {
    alpha_2_code: 'PN',
    alpha_3_code: 'PCN',
    country_code: '+870',
    en_short_name: 'Pitcairn',
    nationality: 'Pitcairn Island',
  },
  {
    alpha_2_code: 'PL',
    alpha_3_code: 'POL',
    country_code: '+48',
    en_short_name: 'Poland',
    nationality: 'Polish',
  },
  {
    alpha_2_code: 'PT',
    alpha_3_code: 'PRT',
    country_code: '+351',
    en_short_name: 'Portugal',
    nationality: 'Portuguese',
  },
  {
    alpha_2_code: 'PR',
    alpha_3_code: 'PRI',
    country_code: '+1939',
    en_short_name: 'Puerto Rico',
    nationality: 'Puerto Rican',
  },
  {
    alpha_2_code: 'QA',
    alpha_3_code: 'QAT',
    country_code: '+974',
    en_short_name: 'Qatar',
    nationality: 'Qatari',
  },
  {
    alpha_2_code: 'RE',
    alpha_3_code: 'REU',
    country_code: '+262',
    en_short_name: 'Réunion',
    nationality: 'Réunionese, Réunionnais',
  },
  {
    alpha_2_code: 'RO',
    alpha_3_code: 'ROU',
    country_code: '+40',
    en_short_name: 'Romania',
    nationality: 'Romanian',
  },
  {
    alpha_2_code: 'RU',
    alpha_3_code: 'RUS',
    country_code: '+7',
    en_short_name: 'Russian Federation',
    nationality: 'Russian',
  },
  {
    alpha_2_code: 'RW',
    alpha_3_code: 'RWA',
    country_code: '+250',
    en_short_name: 'Rwanda',
    nationality: 'Rwandan',
  },
  {
    alpha_2_code: 'BL',
    alpha_3_code: 'BLM',
    country_code: '+590',
    en_short_name: 'Saint Barthélemy',
    nationality: 'Barthélemois',
  },
  {
    alpha_2_code: 'SH',
    alpha_3_code: 'SHN',
    country_code: '+290',
    en_short_name: 'Saint Helena, Ascension and Tristan da Cunha',
    nationality: 'Saint Helenian',
  },
  {
    alpha_2_code: 'KN',
    alpha_3_code: 'KNA',
    country_code: '+1869',
    en_short_name: 'Saint Kitts and Nevis',
    nationality: 'Kittitian or Nevisian',
  },
  {
    alpha_2_code: 'LC',
    alpha_3_code: 'LCA',
    country_code: '+1758',
    en_short_name: 'Saint Lucia',
    nationality: 'Saint Lucian',
  },
  {
    alpha_2_code: 'MF',
    alpha_3_code: 'MAF',
    country_code: '+590',
    en_short_name: 'Saint Martin (French part)',
    nationality: 'Saint-Martinoise',
  },
  {
    alpha_2_code: 'PM',
    alpha_3_code: 'SPM',
    country_code: '+508',
    en_short_name: 'Saint Pierre and Miquelon',
    nationality: 'Saint-Pierrais or Miquelonnais',
  },
  {
    alpha_2_code: 'VC',
    alpha_3_code: 'VCT',
    country_code: '+1784',
    en_short_name: 'Saint Vincent and the Grenadines',
    nationality: 'Saint Vincentian, Vincentian',
  },
  {
    alpha_2_code: 'WS',
    alpha_3_code: 'WSM',
    country_code: '+685',
    en_short_name: 'Samoa',
    nationality: 'Samoan',
  },
  {
    alpha_2_code: 'SM',
    alpha_3_code: 'SMR',
    country_code: '+378',
    en_short_name: 'San Marino',
    nationality: 'Sammarinese',
  },
  {
    alpha_2_code: 'ST',
    alpha_3_code: 'STP',
    country_code: '+239',
    en_short_name: 'Sao Tome and Principe',
    nationality: 'São Toméan',
  },
  {
    alpha_2_code: 'SA',
    alpha_3_code: 'SAU',
    country_code: '+966',
    en_short_name: 'Saudi Arabia',
    nationality: 'Saudi, Saudi Arabian',
  },
  {
    alpha_2_code: 'SN',
    alpha_3_code: 'SEN',
    country_code: '+221',
    en_short_name: 'Senegal',
    nationality: 'Senegalese',
  },
  {
    alpha_2_code: 'RS',
    alpha_3_code: 'SRB',
    country_code: '+381',
    en_short_name: 'Serbia',
    nationality: 'Serbian',
  },
  {
    alpha_2_code: 'SC',
    alpha_3_code: 'SYC',
    country_code: '+248',
    en_short_name: 'Seychelles',
    nationality: 'Seychellois',
  },
  {
    alpha_2_code: 'SL',
    alpha_3_code: 'SLE',
    country_code: '+232',
    en_short_name: 'Sierra Leone',
    nationality: 'Sierra Leonean',
  },
  {
    alpha_2_code: 'SG',
    alpha_3_code: 'SGP',
    country_code: '+65',
    en_short_name: 'Singapore',
    nationality: 'Singaporean',
  },
  {
    alpha_2_code: 'SX',
    alpha_3_code: 'SXM',
    country_code: '+1721',
    en_short_name: 'Sint Maarten (Dutch part)',
    nationality: 'Sint Maarten',
  },
  {
    alpha_2_code: 'SK',
    alpha_3_code: 'SVK',
    country_code: '+421',
    en_short_name: 'Slovakia',
    nationality: 'Slovak',
  },
  {
    alpha_2_code: 'SI',
    alpha_3_code: 'SVN',
    country_code: '+386',
    en_short_name: 'Slovenia',
    nationality: 'Slovenian, Slovene',
  },
  {
    alpha_2_code: 'SB',
    alpha_3_code: 'SLB',
    country_code: '+677',
    en_short_name: 'Solomon Islands',
    nationality: 'Solomon Island',
  },
  {
    alpha_2_code: 'SO',
    alpha_3_code: 'SOM',
    country_code: '+252',
    en_short_name: 'Somalia',
    nationality: 'Somali, Somalian',
  },
  {
    alpha_2_code: 'ZA',
    alpha_3_code: 'ZAF',
    country_code: '+27',
    en_short_name: 'South Africa',
    nationality: 'South African',
  },
  {
    alpha_2_code: 'GS',
    alpha_3_code: 'SGS',
    country_code: '+500',
    en_short_name: 'South Georgia and the South Sandwich Islands',
    nationality: 'South Georgia or South Sandwich Islands',
  },
  {
    alpha_2_code: 'SS',
    alpha_3_code: 'SSD',
    country_code: '+211',
    en_short_name: 'South Sudan',
    nationality: 'South Sudanese',
  },
  {
    alpha_2_code: 'ES',
    alpha_3_code: 'ESP',
    country_code: '+34',
    en_short_name: 'Spain',
    nationality: 'Spanish',
  },
  {
    alpha_2_code: 'LK',
    alpha_3_code: 'LKA',
    country_code: '+94',
    en_short_name: 'Sri Lanka',
    nationality: 'Sri Lankan',
  },
  {
    alpha_2_code: 'SD',
    alpha_3_code: 'SDN',
    country_code: '+249',
    en_short_name: 'Sudan',
    nationality: 'Sudanese',
  },
  {
    alpha_2_code: 'SR',
    alpha_3_code: 'SUR',
    country_code: '+597',
    en_short_name: 'Suriname',
    nationality: 'Surinamese',
  },
  {
    alpha_2_code: 'SJ',
    alpha_3_code: 'SJM',
    country_code: '+47',
    en_short_name: 'Svalbard and Jan Mayen',
    nationality: 'Svalbard',
  },
  {
    alpha_2_code: 'SZ',
    alpha_3_code: 'SWZ',
    country_code: '+268',
    en_short_name: 'Swaziland',
    nationality: 'Swazi',
  },
  {
    alpha_2_code: 'SE',
    alpha_3_code: 'SWE',
    country_code: '+46',
    en_short_name: 'Sweden',
    nationality: 'Swedish',
  },
  {
    alpha_2_code: 'CH',
    alpha_3_code: 'CHE',
    country_code: '+41',
    en_short_name: 'Switzerland',
    nationality: 'Swiss',
  },
  {
    alpha_2_code: 'SY',
    alpha_3_code: 'SYR',
    country_code: '+963',
    en_short_name: 'Syrian Arab Republic',
    nationality: 'Syrian',
  },
  {
    alpha_2_code: 'TW',
    alpha_3_code: 'TWN',
    country_code: '+886',
    en_short_name: 'Taiwan, Province of China',
    nationality: 'Chinese, Taiwanese',
  },
  {
    alpha_2_code: 'TJ',
    alpha_3_code: 'TJK',
    country_code: '+992',
    en_short_name: 'Tajikistan',
    nationality: 'Tajikistani',
  },
  {
    alpha_2_code: 'TZ',
    alpha_3_code: 'TZA',
    country_code: '+255',
    en_short_name: 'Tanzania, United Republic of',
    nationality: 'Tanzanian',
  },
  {
    alpha_2_code: 'TH',
    alpha_3_code: 'THA',
    country_code: '+66',
    en_short_name: 'Thailand',
    nationality: 'Thai',
  },
  {
    alpha_2_code: 'TL',
    alpha_3_code: 'TLS',
    country_code: '+670',
    en_short_name: 'Timor-Leste',
    nationality: 'Timorese',
  },
  {
    alpha_2_code: 'TG',
    alpha_3_code: 'TGO',
    country_code: '+228',
    en_short_name: 'Togo',
    nationality: 'Togolese',
  },
  {
    alpha_2_code: 'TK',
    alpha_3_code: 'TKL',
    country_code: '+690',
    en_short_name: 'Tokelau',
    nationality: 'Tokelauan',
  },
  {
    alpha_2_code: 'TO',
    alpha_3_code: 'TON',
    country_code: '+676',
    en_short_name: 'Tonga',
    nationality: 'Tongan',
  },
  {
    alpha_2_code: 'TT',
    alpha_3_code: 'TTO',
    country_code: '+1868',
    en_short_name: 'Trinidad and Tobago',
    nationality: 'Trinidadian or Tobagonian',
  },
  {
    alpha_2_code: 'TN',
    alpha_3_code: 'TUN',
    country_code: '+216',
    en_short_name: 'Tunisia',
    nationality: 'Tunisian',
  },
  {
    alpha_2_code: 'TR',
    alpha_3_code: 'TUR',
    country_code: '+90',
    en_short_name: 'Turkey',
    nationality: 'Turkish',
  },
  {
    alpha_2_code: 'TM',
    alpha_3_code: 'TKM',
    country_code: '+993',
    en_short_name: 'Turkmenistan',
    nationality: 'Turkmen',
  },
  {
    alpha_2_code: 'TC',
    alpha_3_code: 'TCA',
    country_code: '+1649',
    en_short_name: 'Turks and Caicos Islands',
    nationality: 'Turks and Caicos Island',
  },
  {
    alpha_2_code: 'TV',
    alpha_3_code: 'TUV',
    country_code: '+688',
    en_short_name: 'Tuvalu',
    nationality: 'Tuvaluan',
  },
  {
    alpha_2_code: 'UG',
    alpha_3_code: 'UGA',
    country_code: '+256',
    en_short_name: 'Uganda',
    nationality: 'Ugandan',
  },
  {
    alpha_2_code: 'UA',
    alpha_3_code: 'UKR',
    country_code: '+380',
    en_short_name: 'Ukraine',
    nationality: 'Ukrainian',
  },
  {
    alpha_2_code: 'AE',
    alpha_3_code: 'ARE',
    country_code: '+971',
    en_short_name: 'United Arab Emirates',
    nationality: 'Emirati, Emirian, Emiri',
  },
  {
    alpha_2_code: 'GB',
    alpha_3_code: 'GBR',
    country_code: '+44',
    en_short_name: 'United Kingdom',
    nationality: 'British, UK',
  },
  {
    alpha_2_code: 'US',
    alpha_3_code: 'USA',
    country_code: '+1',
    en_short_name: 'United States of America',
    nationality: 'American',
  },
  {
    alpha_2_code: 'UY',
    alpha_3_code: 'URY',
    country_code: '+598',
    en_short_name: 'Uruguay',
    nationality: 'Uruguayan',
  },
  {
    alpha_2_code: 'UZ',
    alpha_3_code: 'UZB',
    country_code: '+998',
    en_short_name: 'Uzbekistan',
    nationality: 'Uzbekistani, Uzbek',
  },
  {
    alpha_2_code: 'VU',
    alpha_3_code: 'VUT',
    country_code: '+678',
    en_short_name: 'Vanuatu',
    nationality: 'Ni-Vanuatu, Vanuatuan',
  },
  {
    alpha_2_code: 'VE',
    alpha_3_code: 'VEN',
    country_code: '+58',
    en_short_name: 'Venezuela (Bolivarian Republic of)',
    nationality: 'Venezuelan',
  },
  {
    alpha_2_code: 'VN',
    alpha_3_code: 'VNM',
    country_code: '+84',
    en_short_name: 'Vietnam',
    nationality: 'Vietnamese',
  },
  {
    alpha_2_code: 'VG',
    alpha_3_code: 'VGB',
    country_code: '+1284',
    en_short_name: 'Virgin Islands (British)',
    nationality: 'British Virgin Island',
  },
  {
    alpha_2_code: 'VI',
    alpha_3_code: 'VIR',
    country_code: '+1340',
    en_short_name: 'Virgin Islands (U.S.)',
    nationality: 'U.S. Virgin Island',
  },
  {
    alpha_2_code: 'WF',
    alpha_3_code: 'WLF',
    country_code: '+681',
    en_short_name: 'Wallis and Futuna',
    nationality: 'Wallis and Futuna, Wallisian or Futunan',
  },
  {
    alpha_2_code: 'EH',
    alpha_3_code: 'ESH',
    country_code: '+212',
    en_short_name: 'Western Sahara',
    nationality: 'Sahrawi, Sahrawian, Sahraouian',
  },
  {
    alpha_2_code: 'YE',
    alpha_3_code: 'YEM',
    country_code: '+967',
    en_short_name: 'Yemen',
    nationality: 'Yemeni',
  },
  {
    alpha_2_code: 'ZM',
    alpha_3_code: 'ZMB',
    country_code: '+260',
    en_short_name: 'Zambia',
    nationality: 'Zambian',
  },
  {
    alpha_2_code: 'ZW',
    alpha_3_code: 'ZWE',
    country_code: '+263',
    en_short_name: 'Zimbabwe',
    nationality: 'Zimbabwean',
  },
]