// @flow
export type CountryDetailsT = {
  alpha_2_code: string,
  alpha_3_code: string,
  country_code: string,
  en_short_name: CountriesT,
  nationality: NationalitiesT,
}

export type NationalitiesT =
  | 'Afghan'
  | 'Åland Island'
  | 'Albanian'
  | 'Algerian'
  | 'American Samoan'
  | 'Andorran'
  | 'Angolan'
  | 'Anguillan'
  | 'Antarctic'
  | 'Antiguan or Barbudan'
  | 'Argentine'
  | 'Armenian'
  | 'Aruban'
  | 'Australian'
  | 'Austrian'
  | 'Azerbaijani| Azeri'
  | 'Bahamian'
  | 'Bahraini'
  | 'Bangladeshi'
  | 'Barbadian'
  | 'Belarusian'
  | 'Belgian'
  | 'Belizean'
  | 'Beninese| Beninois'
  | 'Bermudian| Bermudan'
  | 'Bhutanese'
  | 'Bolivian'
  | 'Bonaire'
  | 'Bosnian or Herzegovinian'
  | 'Motswana| Botswanan'
  | 'Bouvet Island'
  | 'Brazilian'
  | 'BIOT'
  | 'Bruneian'
  | 'Bulgarian'
  | 'Burkinabé'
  | 'Burundian'
  | 'Cabo Verdean'
  | 'Cambodian'
  | 'Cameroonian'
  | 'Canadian'
  | 'Caymanian'
  | 'Central African'
  | 'Chadian'
  | 'Chilean'
  | 'Chinese'
  | 'Christmas Island'
  | 'Cocos Island'
  | 'Colombian'
  | 'Comoran| Comorian'
  | 'Congolese'
  | 'Cook Island'
  | 'Costa Rican'
  | 'Ivorian'
  | 'Croatian'
  | 'Cuban'
  | 'Curaçaoan'
  | 'Cypriot'
  | 'Czech'
  | 'Danish'
  | 'Djiboutian'
  | 'Dominican'
  | 'Ecuadorian'
  | 'Egyptian'
  | 'Salvadoran'
  | 'Equatorial Guinean| Equatoguinean'
  | 'Eritrean'
  | 'Estonian'
  | 'Ethiopian'
  | 'Falkland Island'
  | 'Faroese'
  | 'Fijian'
  | 'Finnish'
  | 'French'
  | 'French Guianese'
  | 'French Polynesian'
  | 'French Southern Territories'
  | 'Gabonese'
  | 'Gambian'
  | 'Georgian'
  | 'German'
  | 'Ghanaian'
  | 'Gibraltar'
  | 'Greek| Hellenic'
  | 'Greenlandic'
  | 'Grenadian'
  | 'Guadeloupe'
  | 'Guamanian| Guambat'
  | 'Guatemalan'
  | 'Channel Island'
  | 'Guinean'
  | 'Bissau-Guinean'
  | 'Guyanese'
  | 'Haitian'
  | 'Heard Island or McDonald Islands'
  | 'Vatican'
  | 'Honduran'
  | 'Hong Kong| Hong Kongese'
  | 'Hungarian| Magyar'
  | 'Icelandic'
  | 'Indian'
  | 'Indonesian'
  | 'Iranian| Persian'
  | 'Iraqi'
  | 'Irish'
  | 'Manx'
  | 'Israeli'
  | 'Italian'
  | 'Jamaican'
  | 'Japanese'
  | 'Channel Island'
  | 'Jordanian'
  | 'Kazakhstani| Kazakh'
  | 'Kenyan'
  | 'I-Kiribati'
  | 'North Korean'
  | 'South Korean'
  | 'Kosovan'
  | 'Kuwaiti'
  | 'Kyrgyzstani| Kyrgyz| Kirgiz| Kirghiz'
  | 'Lao| Laotian'
  | 'Latvian'
  | 'Lebanese'
  | 'Basotho'
  | 'Liberian'
  | 'Libyan'
  | 'Liechtenstein'
  | 'Lithuanian'
  | 'Luxembourg| Luxembourgish'
  | 'Macanese| Chinese'
  | 'Macedonian'
  | 'Malagasy'
  | 'Malawian'
  | 'Malaysian'
  | 'Maldivian'
  | 'Malian| Malinese'
  | 'Maltese'
  | 'Marshallese'
  | 'Martiniquais| Martinican'
  | 'Mauritanian'
  | 'Mauritian'
  | 'Mahoran'
  | 'Mexican'
  | 'Micronesian'
  | 'Moldovan'
  | 'Monégasque| Monacan'
  | 'Mongolian'
  | 'Montenegrin'
  | 'Montserratian'
  | 'Moroccan'
  | 'Mozambican'
  | 'Burmese'
  | 'Namibian'
  | 'Nauruan'
  | 'Nepali| Nepalese'
  | 'Dutch| Netherlandic'
  | 'New Caledonian'
  | 'New Zealand| NZ'
  | 'Nicaraguan'
  | 'Nigerien'
  | 'Nigerian'
  | 'Niuean'
  | 'Norfolk Island'
  | 'Northern Marianan'
  | 'Norwegian'
  | 'Omani'
  | 'Pakistani'
  | 'Palauan'
  | 'Palestinian'
  | 'Panamanian'
  | 'Papua New Guinean| Papuan'
  | 'Paraguayan'
  | 'Peruvian'
  | 'Philippine| Filipino'
  | 'Pitcairn Island'
  | 'Polish'
  | 'Portuguese'
  | 'Puerto Rican'
  | 'Qatari'
  | 'Réunionese| Réunionnais'
  | 'Romanian'
  | 'Russian'
  | 'Rwandan'
  | 'Barthélemois'
  | 'Saint Helenian'
  | 'Kittitian or Nevisian'
  | 'Saint Lucian'
  | 'Saint-Martinoise'
  | 'Saint-Pierrais or Miquelonnais'
  | 'Saint Vincentian| Vincentian'
  | 'Samoan'
  | 'Sammarinese'
  | 'São Toméan'
  | 'Saudi| Saudi Arabian'
  | 'Senegalese'
  | 'Serbian'
  | 'Seychellois'
  | 'Sierra Leonean'
  | 'Singaporean'
  | 'Sint Maarten'
  | 'Slovak'
  | 'Slovenian| Slovene'
  | 'Solomon Island'
  | 'Somali| Somalian'
  | 'South African'
  | 'South Georgia or South Sandwich Islands'
  | 'South Sudanese'
  | 'Spanish'
  | 'Sri Lankan'
  | 'Sudanese'
  | 'Surinamese'
  | 'Svalbard'
  | 'Swazi'
  | 'Swedish'
  | 'Swiss'
  | 'Syrian'
  | 'Chinese| Taiwanese'
  | 'Tajikistani'
  | 'Tanzanian'
  | 'Thai'
  | 'Timorese'
  | 'Togolese'
  | 'Tokelauan'
  | 'Tongan'
  | 'Trinidadian or Tobagonian'
  | 'Tunisian'
  | 'Turkish'
  | 'Turkmen'
  | 'Turks and Caicos Island'
  | 'Tuvaluan'
  | 'Ugandan'
  | 'Ukrainian'
  | 'Emirati| Emirian| Emiri'
  | 'British| UK'
  | 'American'
  | 'American'
  | 'Uruguayan'
  | 'Uzbekistani| Uzbek'
  | 'Ni-Vanuatu| Vanuatuan'
  | 'Venezuelan'
  | 'Vietnamese'
  | 'British Virgin Island'
  | 'U.S. Virgin Island'
  | 'Wallis and Futuna| Wallisian or Futunan'
  | 'Sahrawi| Sahrawian| Sahraouian'
  | 'Yemeni'
  | 'Zambian'
  | 'Zimbabwean'

export type CountriesT =
  | 'Afghanistan'
  | 'Åland Islands'
  | 'Albania'
  | 'Algeria'
  | 'American Samoa'
  | 'Andorra'
  | 'Angola'
  | 'Anguilla'
  | 'Antarctica'
  | 'Antigua and Barbuda'
  | 'Argentina'
  | 'Armenia'
  | 'Aruba'
  | 'Australia'
  | 'Austria'
  | 'Azerbaijan'
  | 'Bahamas'
  | 'Bahrain'
  | 'Bangladesh'
  | 'Barbados'
  | 'Belarus'
  | 'Belgium'
  | 'Belize'
  | 'Benin'
  | 'Bermuda'
  | 'Bhutan'
  | 'Bolivia (Plurinational State of)'
  | 'Bonaire| Sint Eustatius and Saba'
  | 'Bosnia and Herzegovina'
  | 'Botswana'
  | 'Bouvet Island'
  | 'Brazil'
  | 'British Indian Ocean Territory'
  | 'Brunei Darussalam'
  | 'Bulgaria'
  | 'Burkina Faso'
  | 'Burundi'
  | 'Cabo Verde'
  | 'Cambodia'
  | 'Cameroon'
  | 'Canada'
  | 'Cayman Islands'
  | 'Central African Republic'
  | 'Chad'
  | 'Chile'
  | 'China'
  | 'Christmas Island'
  | 'Cocos (Keeling) Islands'
  | 'Colombia'
  | 'Comoros'
  | 'Congo (Republic of the)'
  | 'Congo (Democratic Republic of the)'
  | 'Cook Islands'
  | 'Costa Rica'
  | 'Côte d\'Ivoire'
  | 'Croatia'
  | 'Cuba'
  | 'Curaçao'
  | 'Cyprus'
  | 'Czech Republic'
  | 'Denmark'
  | 'Djibouti'
  | 'Dominica'
  | 'Dominican Republic'
  | 'Ecuador'
  | 'Egypt'
  | 'El Salvador'
  | 'Equatorial Guinea'
  | 'Eritrea'
  | 'Estonia'
  | 'Ethiopia'
  | 'Falkland Islands (Malvinas)'
  | 'Faroe Islands'
  | 'Fiji'
  | 'Finland'
  | 'France'
  | 'French Guiana'
  | 'French Polynesia'
  | 'French Southern Territories'
  | 'Gabon'
  | 'Gambia'
  | 'Georgia'
  | 'Germany'
  | 'Ghana'
  | 'Gibraltar'
  | 'Greece'
  | 'Greenland'
  | 'Grenada'
  | 'Guadeloupe'
  | 'Guam'
  | 'Guatemala'
  | 'Guernsey'
  | 'Guinea'
  | 'Guinea-Bissau'
  | 'Guyana'
  | 'Haiti'
  | 'Heard Island and McDonald Islands'
  | 'Vatican City State'
  | 'Honduras'
  | 'Hong Kong'
  | 'Hungary'
  | 'Iceland'
  | 'India'
  | 'Indonesia'
  | 'Iran'
  | 'Iraq'
  | 'Ireland'
  | 'Isle of Man'
  | 'Israel'
  | 'Italy'
  | 'Jamaica'
  | 'Japan'
  | 'Jersey'
  | 'Jordan'
  | 'Kazakhstan'
  | 'Kenya'
  | 'Kiribati'
  | 'Korea (Democratic People\'s Republic of)'
  | 'Korea (Republic of)'
  | 'Kuwait'
  | 'Kosovo'
  | 'Kyrgyzstan'
  | 'Lao People\'s Democratic Republic'
  | 'Latvia'
  | 'Lebanon'
  | 'Lesotho'
  | 'Liberia'
  | 'Libya'
  | 'Liechtenstein'
  | 'Lithuania'
  | 'Luxembourg'
  | 'Macao'
  | 'Macedonia (the former Yugoslav Republic of)'
  | 'Madagascar'
  | 'Malawi'
  | 'Malaysia'
  | 'Maldives'
  | 'Mali'
  | 'Malta'
  | 'Marshall Islands'
  | 'Martinique'
  | 'Mauritania'
  | 'Mauritius'
  | 'Mayotte'
  | 'Mexico'
  | 'Micronesia (Federated States of)'
  | 'Moldova (Republic of)'
  | 'Monaco'
  | 'Mongolia'
  | 'Montenegro'
  | 'Montserrat'
  | 'Morocco'
  | 'Mozambique'
  | 'Myanmar'
  | 'Namibia'
  | 'Nauru'
  | 'Nepal'
  | 'Netherlands'
  | 'New Caledonia'
  | 'New Zealand'
  | 'Nicaragua'
  | 'Niger'
  | 'Nigeria'
  | 'Niue'
  | 'Norfolk Island'
  | 'Northern Mariana Islands'
  | 'Norway'
  | 'Oman'
  | 'Pakistan'
  | 'Palau'
  | 'Palestine| State of'
  | 'Panama'
  | 'Papua New Guinea'
  | 'Paraguay'
  | 'Peru'
  | 'Philippines'
  | 'Pitcairn'
  | 'Poland'
  | 'Portugal'
  | 'Puerto Rico'
  | 'Qatar'
  | 'Réunion'
  | 'Romania'
  | 'Russian Federation'
  | 'Rwanda'
  | 'Saint Barthélemy'
  | 'Saint Helena| Ascension and Tristan da Cunha'
  | 'Saint Kitts and Nevis'
  | 'Saint Lucia'
  | 'Saint Martin (French part)'
  | 'Saint Pierre and Miquelon'
  | 'Saint Vincent and the Grenadines'
  | 'Samoa'
  | 'San Marino'
  | 'Sao Tome and Principe'
  | 'Saudi Arabia'
  | 'Senegal'
  | 'Serbia'
  | 'Seychelles'
  | 'Sierra Leone'
  | 'Singapore'
  | 'Sint Maarten (Dutch part)'
  | 'Slovakia'
  | 'Slovenia'
  | 'Solomon Islands'
  | 'Somalia'
  | 'South Africa'
  | 'South Georgia and the South Sandwich Islands'
  | 'South Sudan'
  | 'Spain'
  | 'Sri Lanka'
  | 'Sudan'
  | 'Suriname'
  | 'Svalbard and Jan Mayen'
  | 'Swaziland'
  | 'Sweden'
  | 'Switzerland'
  | 'Syrian Arab Republic'
  | 'Taiwan| Province of China'
  | 'Tajikistan'
  | 'Tanzania| United Republic of'
  | 'Thailand'
  | 'Timor-Leste'
  | 'Togo'
  | 'Tokelau'
  | 'Tonga'
  | 'Trinidad and Tobago'
  | 'Tunisia'
  | 'Turkey'
  | 'Turkmenistan'
  | 'Turks and Caicos Islands'
  | 'Tuvalu'
  | 'Uganda'
  | 'Ukraine'
  | 'United Arab Emirates'
  | 'United Kingdom'
  | 'United States Minor Outlying Islands'
  | 'United States of America'
  | 'Uruguay'
  | 'Uzbekistan'
  | 'Vanuatu'
  | 'Venezuela (Bolivarian Republic of)'
  | 'Vietnam'
  | 'Virgin Islands (British)'
  | 'Virgin Islands (U.S.)'
  | 'Wallis and Futuna'
  | 'Western Sahara'
  | 'Yemen'
  | 'Zambia'
  | 'Zimbabwe'